# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: 0BSD
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.2/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: flux-system
stringData:
  username: ENC[AES256_GCM,data:J/VX,iv:5J5R5Em0vGtZvtZb4PuMZgKqoRTiEOcunJlaf4/B9h0=,tag:Ohvh/MG+OIzALwAVmgFAsQ==,type:str]
  password: ENC[AES256_GCM,data:GxCvGv5QyxAVeISxE4xE3qzHzWshyJ4s1v7SuM+tkxnQm3qSQoal9A==,iv:zbpIek+pRgqPEQu3QaMxIfGEqKOavfmLRel4m8JNQ8A=,tag:B3AlN13eryYbRAiX30h2MA==,type:str]
sops:
  age:
    - recipient: age16k03wpjydrcr2wk68f0q9ypdxvh7vsy0fpx4lq72nc50zln8xf3qvkjxas
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWGtoZGFTY2xKZ0hBNzNW
        NkNWb3pxdHNLOGlMRDhGYnE3Njd1bTNSVzJjCnFTN3gzWU0ycHo4dmRPNHIraFNV
        ZzFhRkl5VXh6Nnp3ME9GMlZ2R2NXNmsKLS0tIFZ2UHg2VnptMzQwN1AxK3c1U2hP
        U2pnblJqUDlocUFYdmdMYngxbXdLejQKj31MstZZB8Sff6ZAXW6z02oQCkkf3/mC
        M/Ddci4+sxlldL1OtGPHhz3EORDLsjx9LRry0LqXoqNmpTpocTkQCg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-06T18:07:39Z"
  mac: ENC[AES256_GCM,data:v2rw0lfKLkzj+mrtbonJ9Clb5YXkgmCSGYJTrjsB4DKJruuzpIhg85Ap8oMhGz5bMPs/FX3hTk8UmgRbtPg+BVwmnT51KZ+iwmK/dITEmQKQqfmamB9b6lLKE+eiUj0TeixCuFclbJTxB6RFAni/ZZfh2tn1heJKTWonIebZFxU=,iv:QnSlYUlHLk4X9LWWZ2Vir0kpBuuGjDRz3NEJt5g/8CY=,tag:nibVlWaiAHCnZrliCQs+Lw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
