# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: 0BSD
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.2/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: flux-system
stringData:
  username: ENC[AES256_GCM,data:jbyUejtsmQ==,iv:Rk2SOnplK4nrnxusY4vTwFrfmXDEyV/0vJ9HDpswPpc=,tag:fyhIk3smCV6jTHtUE25CMg==,type:str]
  password: ENC[AES256_GCM,data:gA4kNjF0QzHmOcqKM4pgMFpzj9Ag5rkzXS3C3uH71b49fnEQwlJ1MA==,iv:fuOHwO2ukdEGGXW077+tweXKhm86eVH1shbjEK+3g1c=,tag:g+cDyYEEDIBFXyzIPa5LlQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWGtoZGFTY2xKZ0hBNzNW
        NkNWb3pxdHNLOGlMRDhGYnE3Njd1bTNSVzJjCnFTN3gzWU0ycHo4dmRPNHIraFNV
        ZzFhRkl5VXh6Nnp3ME9GMlZ2R2NXNmsKLS0tIFZ2UHg2VnptMzQwN1AxK3c1U2hP
        U2pnblJqUDlocUFYdmdMYngxbXdLejQKj31MstZZB8Sff6ZAXW6z02oQCkkf3/mC
        M/Ddci4+sxlldL1OtGPHhz3EORDLsjx9LRry0LqXoqNmpTpocTkQCg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16k03wpjydrcr2wk68f0q9ypdxvh7vsy0fpx4lq72nc50zln8xf3qvkjxas
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-27T11:32:53Z"
  mac: ENC[AES256_GCM,data:OYLdMrQ1+Gk6eorjBfwEw+AHUoW1AiP3EMsaky00FdstuQ8TOmOAlEeFBdED8fcg2ITfPBy3l/UfGrhCNDXULOZoKXzEWenUIqalQsc161H1cEgoy/hunYBK4dG5mBSyrBaiFstYllJCHZ0PnCRU5wUOVGB1JpL7FhPiJv1DPt8=,iv:WbEfikbJ7+NiAftQPYThqmzGs4ta3kG9b/UAnj+9V6Q=,tag:czmoec6SvHAHysjeV7YobQ==,type:str]
  version: 3.13.3
