# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: 0BSD

creation_rules:
  - path_regex: .*\.sops\.ya?ml
    encrypted_regex: ^(data|stringData)$
    age: age16k03wpjydrcr2wk68f0q9ypdxvh7vsy0fpx4lq72nc50zln8xf3qvkjxas
stores:
  yaml:
    indent: 2
