# SPDX-FileCopyrightText: SoupGlasses
# SPDX-License-Identifier: CC0-1.0

creation_rules:
  - path_regex: .*\.yaml
    encrypted_regex: ^(data|stringData)$
    age: age173s68yyn94yk2tndtuk92ynhxuqsy0g0wdur0vygckra5c54qd3qy5wwe0
