# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: MIT

# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  talos:
    taskfile: .taskfiles/talos.yaml
    dir: .
  flux:
    taskfile: .taskfiles/flux.yaml
    dir: .
  kube:
    taskfile: .taskfiles/kubernetes.yaml
    dir: .
  license:
    taskfile: .taskfiles/license.yaml
    dir: .
