# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: MIT
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-ovh
spec:
  interval: 30m
  chart:
    spec:
      chart: cert-manager-webhook-ovh
      version: 0.9.16
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-ovh
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    configVersion: 0.0.2
    groupName: acme.${DOMAIN}
    certManager:
      namespace: cert-manager
      serviceAccountName: cert-manager
    issuers:
      - name: ovh-dns01-production
        create: true
        kind: ClusterIssuer
        acmeServerUrl: https://acme-v02.api.letsencrypt.org/directory
        profile: tlsserver
        email: acme@${DOMAIN}
        ovhEndpointName: ovh-eu
        ovhAuthenticationMethod: application
        ovhAuthenticationRef:
          applicationKeyRef:
            name: ovh-credentials
            key: applicationKey
          applicationSecretRef:
            name: ovh-credentials
            key: applicationSecret
          applicationConsumerKeyRef:
            name: ovh-credentials
            key: applicationConsumerKey
      - name: ovh-dns01-staging
        create: true
        kind: ClusterIssuer
        acmeServerUrl: https://acme-staging-v02.api.letsencrypt.org/directory
        profile: tlsserver
        email: acme@${DOMAIN}
        ovhEndpointName: ovh-eu
        ovhAuthenticationMethod: application
        ovhAuthenticationRef:
          applicationKeyRef:
            name: ovh-credentials
            key: applicationKey
          applicationSecretRef:
            name: ovh-credentials
            key: applicationSecret
          applicationConsumerKeyRef:
            name: ovh-credentials
            key: applicationConsumerKey
