# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: 0BSD
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.2/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ovh-credentials
stringData:
  applicationKey: ENC[AES256_GCM,data:ECr74lXYUlJZPwimAAThrA==,iv:PQv+ZoBm5/DSdKn+tAzRmnYaPfMJh203btJibf8n7Bk=,tag:+ZyU7Ihk3nfs0/n4WrqTcQ==,type:str]
  applicationSecret: ENC[AES256_GCM,data:tBaORtT77tGkKdJnujwb9Y5tjFaTCRddC4dz1S/UXDk=,iv:5DjuIRW6+zCWh+7nV4FUhvJQlR3/+eBl3MABqhBu8RM=,tag:TVGyKGftCiiAKTfW25U9uQ==,type:str]
  applicationConsumerKey: ENC[AES256_GCM,data:ktv+urz39nDTCxPaDpts8s8JlnXplfm98m921o+KuNo=,iv:ho3nnwfcB8JuD2L2p0n9occyC1k/tvhZMTwLwvlD2b4=,tag:yGLQ2SlAaeRTYAM5immW9w==,type:str]
sops:
  age:
    - recipient: age16k03wpjydrcr2wk68f0q9ypdxvh7vsy0fpx4lq72nc50zln8xf3qvkjxas
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkeFhFYlA2blVvQUZqb3pj
        ZUFMQm1JWURqa0cySVRwQmN2dkp0ZmNxS1JJCkdaSHpDUnBmalFqTVV3djZNczZJ
        azFYSk5hTTV5WEdNUjVJUDRvYUw0TlUKLS0tIHlQa08zWTVHV1N0bjM4eFQrNHhi
        d2FwZnhMTnoxSW13ZWpmaytCRHlyWFkKiGvKGUh87pArixMQAqh9tYcOOd1YpSdv
        t2hDZd96ROYmeAIQAsEBE6r1R0OFJGkvSGDZmPZvEvQIsgQVp7sltA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-12T00:21:43Z"
  mac: ENC[AES256_GCM,data:MUGjIsaHC786MV4MO21pA3U7EVg7DC9LyajsUPf1CUcaVyAeLzWaAIrYgUHjFg9RSYL8ZEtRuf3umX+mniGBESfb4oDtPAXOAVyvULGNyx+hOAEFPUXrGmNH0N3WWLNWOzUaXmoIhdBjm82wOr+d+g/bOV/d2dxL0+r4vx7ZxIg=,iv:znUUlp0NlNZuP07qMbde/uah3SBsub492P4YMLwSiKg=,tag:X8Q0RV8SMYk3dNXPHsjZzQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
