# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: 0BSD

apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}
spec:
  sourcePVC: ${APP}
  trigger:
    schedule: ${VOLSYNC_SCHEDULE:=15 6 * * *}
  restic:
    accessModes:
      - ${VOLSYNC_SNAP_ACCESSMODES:=ReadWriteOnce}
    cacheAccessModes:
      - ${VOLSYNC_CACHE_ACCESSMODES:=ReadWriteOnce}
    cacheCapacity: ${VOLSYNC_CACHE_CAPACITY:=5Gi}
    cacheStorageClassName: ${VOLSYNC_CACHE_SNAPSHOTCLASS:=openebs-hostpath}
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=1000}
      runAsGroup: ${VOLSYNC_PGID:=1000}
      fsGroup: ${VOLSYNC_PGID:=1000}
    repository: volsync-${APP}
    pruneIntervalDays: 14
    retain:
      daily: 7
      weekly: 4
    storageClassName: ${VOLSYNC_STORAGECLASS:=openebs-zfs}
    volumeSnapshotClassName: ${VOLSYNC_SNAPSHOTCLASS:=openebs-zfs-snapshot}
