# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: 0BSD
apiVersion: v1
kind: Secret
metadata:
  name: volsync-${APP}
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:6xvzv6L9s/9PqvTvd6wZ4Y+52vlikRW643z1w1nhjtQ5gn4fibTDjUgv7K3Ct3vHZQg=,iv:TBHanG22aCTk1xBXEkNJio1qSxZLSo0pNZHtGMvJH7k=,tag:/FipyNi1yMESetvPGM+ReA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:7NQoU6liLU80t7sULWcYdMod+7capb/bGE7Q0nMubN30DrfnLlzSN1i4sME=,iv:D9wou1U8a8eD0Xwp/pIjCc6UxetGD0T4LX66oc/tj2M=,tag:oq/5M/WVZ0qpk/8qpWJqyw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/vgo255Xird/PPnwucDMaZwTD6Q=,iv:U+A4o8A6qzAo5bUu5qdR1bweel3BEJl+jmTlUhnGq5M=,tag:pLDyyvIg8qmboqf8TkSV7Q==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:4tlB5/uZmud7utFXoR5uX8Ssqgvq4L1loIcHNYsrfenA43LQg4PUYw==,iv:10y1crwDJm5mONJ6BQnWo9fqIdDb+6OcXSs2Em94UhY=,tag:hyCVO6Zm7NdtGU6pi/eeVg==,type:str]
sops:
  age:
    - recipient: age16k03wpjydrcr2wk68f0q9ypdxvh7vsy0fpx4lq72nc50zln8xf3qvkjxas
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WkFSVGJ2SDhIbC9nQ1V5
        eVZ6UjZzOUVBckpQaDg1Tk5FaXhHN01xUjM0CkxXOEZwS2V4b1VCYzlVTnRVK0R3
        bzI4bFp6cDh2SUh3QnVQd2REUUVMWTgKLS0tIGNjS1B5YVUyZSswR3BweWo1OXVX
        UzJMeXNTd0IrRWJIdTNucG5McWxmZVkK/oFGo6pHhzf9lbnybRxJI6V8CuZKQg2Y
        ncnsitzOGUk06aifFOwvf3IOm28JbTI/Gytz49WbK9tFf9Q9BKTL1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T12:19:52Z"
  mac: ENC[AES256_GCM,data:8GABYyb/1xztm28Unzg9XUSJj/AHnjbiMViZIKohzHRHpnUYDHKZpGdohfZLPkFDuM4QhS4QtPAtVzTEk/zp4/P9r6+asEEhWfYcmwixpFytvLbW6viyjS/Yt9+bMJzsUsqLeq1TdGxd2YZA+5/oAIB4z1EdqAgFEPx709wgqOQ=,iv:jh3EuX1BQzDkk0IjmatsinCHlM+gpa1mUeFddbm7K7E=,tag:POgQG8M7kcHHv2KNTrPJQA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
