# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: MIT

# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.2/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-${APP}
stringData:
  RESTIC_REPOSITORY: ${SECRET_RESTIC_S3_ENDPOINT}/${VOLSYNC_BUCKET_PATH:-${APP}}
  RESTIC_PASSWORD: ${SECRET_RESTIC_PASSWORD}
  AWS_ACCESS_KEY_ID: ${SECRET_RESTIC_AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${SECRET_RESTIC_AWS_SECRET_ACCESS_KEY}
