# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: MIT

# CiliumLoadBalancerIPPool defines the IP pool for BGP LoadBalancer services
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: bgp-pool
  namespace: kube-system
spec:
  blocks:
    - cidr: "172.21.68.10/32"
  # Only allocate to services with the bgp label
  serviceSelector:
    matchLabels:
      bgp: "enabled"
