# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.2-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:KYWD4HqC+OuXpg==,iv:M41+7qd4Qv0PPtZWZ0mGWP1mVmboB84VT5a3NZy63mo=,tag:JwaZXXWqq/0IQv9gw+NVjQ==,type:str]
sops:
  age:
    - recipient: age173s68yyn94yk2tndtuk92ynhxuqsy0g0wdur0vygckra5c54qd3qy5wwe0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cE5hMlEwVURiMVVqWmZx
        UWhZSm9WcE1tL2UrbUZqWU9qMzVPUmFsckdVCnFYblBPREFydWpZNTFyekdxbTVU
        WmxuVGRYcVVvdElIK1kwUmVFbEdKZjQKLS0tIFhKT2UrSnhiUWswaksxamN4ZXZm
        czU5ZytRWFNIUm1aVjJPZlVkcVNMWXcK/B5dW+IEKwQhrVXiz2W+4leu1Drywdn8
        2s+RawuzYUlJWctf8OPY3UKM+KamQS9Z37whdrAWP4yiBH3WFy5v4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-14T20:03:10Z"
  mac: ENC[AES256_GCM,data:I9+pUZDPRq3E4oajrHeMAC2l4Ivot6JZxU/7CTS+jdQdp/ag4nN7muRpqkUfpbJXFReAHZKSqkeXyt2ukRx2BpYbDnsO0E4iuShvHkqkQW/7ckLkwmiUaLf+hAfo38Gfa0R8jUA9zkqpUZ0IRSYhK9WZk1jEoHIvgw5+R8W9YRc=,iv:gjpOjEUxPeEws4tQfy4SqJhvvTXTSEuaoBLFQLs3Ggs=,tag:yk/1MDn2JPWdhtvAmq1pCQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
