# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: 0BSD
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.2/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_PASSWORD: ENC[AES256_GCM,data:dO+1XeoZMdIfhEpCoZrBWLJ1SPklnKxSyatxFJLv,iv:/0FaoTKu8KXTQ+vA9HBh7ipnEdAGwsdDBw79kMFQ51c=,tag:4U1SmCToIuGjF1krjcB3Zw==,type:str]
  SECRET_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:rZI+kS8Pp0oa13lqKLZ+CfzTcXE=,iv:AVHI76dot4VHpjvkh3jtNE2cu0ElQoAcBSU1tmbO/X4=,tag:D+aiPpI5NGOuA1W8+3KYyw==,type:str]
  SECRET_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:LRWqhLyszi80mY0LkVwdwtW3++M2xxHremkkcy1bmABE4u90nElgYA==,iv:NKQaBel8a/eHDYZqpF1N2COMcGOyvUpmUCxgOTRoDNM=,tag:t6uJoc77XDLifMvS2Dbg/A==,type:str]
  SECRET_S3_ENDPOINT: ENC[AES256_GCM,data:CpnR5kCkkZlO1WBsfnA5yHjTSn7u0wiCkWDxXBcAmhrBX3YGyttEslRm,iv:nASLglI9chyg6OWm9lgwEqTQHe0POfEc8wiua1grPDc=,tag:SXaDhCDlhVhE+Dt3fg+GyQ==,type:str]
  SECRET_LDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:KTermO7CJLUxFkKPXmxfNhI6TKoolKiBEZkWGzlUlvqbZMJtHOPe26bk,iv:93ptiBij0FqoqTBjqCwB1f8+ppMucsigSPfiFyfQ1rs=,tag:QgjSFUxkQysrs+HWfwUWsQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqM1ZESDU4QlhheWROdTho
        QW5nNlIzQUIzRmZ4K0ovd2xLS3U0VFpHRlU4CjNpWElhMElEb0lGVmp3V2NFQWpY
        elBGMUd4cVQ3YWdQM2ZqeDArR01wRjAKLS0tIDdWcFphaWNydzZrSVk1SzBDSktH
        UVhwclJZNXNrV0UwcG5uMElEV2tDYUUKp1BTCxDu7wclrV7ReysD1KrhCj5jcahO
        myIwSDG2odswKzekvwzjYhTtZ1qjg+FoBoGZU95HWlDX9RAZNi5o0g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16k03wpjydrcr2wk68f0q9ypdxvh7vsy0fpx4lq72nc50zln8xf3qvkjxas
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-12T10:06:35Z"
  mac: ENC[AES256_GCM,data:HKWHndAW5P6IUkOaYJwFrMuXueltI1sVMmGOq4b0cOiZqEKa8uyEC7FIFzzNPjXVfMWnLNQowkmsiwuATI7WT9vpAPvHcQVUn1Jia+xYIO7zodKOKWVOuJtbM3VG19Q7qRyYFEAWCZM9/wPUeU5A3QymMrOSOneZQjcpoAEmlGk=,iv:yYAj+RCdOMTdafEukpqM5mN+wjDSV7yIa3mLBKi1j20=,tag:b+mAQptQxcKyv14iegY4ww==,type:str]
  version: 3.13.2
