# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: 0BSD
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.2/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:0rJNlEdfl+rsBQ==,iv:kkLZb95zpDsRgyl1uQ3EdLlfJEGWaLT84kR3i8B3kbM=,tag:uNf7QhR+kBLahgBvYXJ4RA==,type:str]
  SECRET_IP_ADDRESS: ENC[AES256_GCM,data:Xukfh+b8JSGmLmFZx0J6,iv:gY5RjH4yg7CH4MyRHz4rbyB+WETKZLIjHIvToQ67+fc=,tag:MxFmXsk1l8g8n+ewF7tiqw==,type:str]
  SECRET_RESTIC_PASSWORD: ENC[AES256_GCM,data:jR2oJ9l/skKQtbdYbkuR6quHkAJjXQHHKxedjHfG,iv:eU1ywmYXv/NDW4Q0/kiG/a0f8/9SURLYbqKGpMGnzvQ=,tag:pZWgaJjtYVQ0xBwFt9SDOg==,type:str]
  SECRET_RESTIC_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:gIw3V4qInhmK/wSnnPAcLVjNPTc=,iv:MuH7Tr4lrC8dq6DE25aD2cYjnWi0G9Lkyn0xTK/aVi4=,tag:htGt3wUk6fSFTOaZm1MB+Q==,type:str]
  SECRET_RESTIC_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:LG93Dny1hP8MzR9TNrls50ckvIsKML4zoamPuRKICM1mO0tbWhwLOw==,iv:8AX0IdviiZLVBFaepeFBYqZuN2lTS5wWYx6UneG1AtI=,tag:gn/GulzxeUKtWyspUOgRVA==,type:str]
  SECRET_RESTIC_S3_ENDPOINT: ENC[AES256_GCM,data:mSrDWkQdSz9hLMelgXNhP6LlvXDS7TWgr382k1SzyPbwGmLzw6VoLiKH,iv:ObWMDhZcoJd21pL435zCwh+3dm2fR5r2SkZiyz7E73M=,tag:ooOELdVFKEYc1wHbv/rOiw==,type:str]
sops:
  age:
    - recipient: age16k03wpjydrcr2wk68f0q9ypdxvh7vsy0fpx4lq72nc50zln8xf3qvkjxas
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqM1ZESDU4QlhheWROdTho
        QW5nNlIzQUIzRmZ4K0ovd2xLS3U0VFpHRlU4CjNpWElhMElEb0lGVmp3V2NFQWpY
        elBGMUd4cVQ3YWdQM2ZqeDArR01wRjAKLS0tIDdWcFphaWNydzZrSVk1SzBDSktH
        UVhwclJZNXNrV0UwcG5uMElEV2tDYUUKp1BTCxDu7wclrV7ReysD1KrhCj5jcahO
        myIwSDG2odswKzekvwzjYhTtZ1qjg+FoBoGZU95HWlDX9RAZNi5o0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T19:40:39Z"
  mac: ENC[AES256_GCM,data:59oMnp7l+8Jlm2CTUoagwPcUS+whVnzpLZhq3B3t3usv9XtILq8m6xtBTZoUKVOCD53kT+fBfHjpdfTs4ISQARJdKTFZvBiBIUyihpw47c+j/ldUKC+ynzvx04qBGMr8XfpCEJXunLQgex+GBL4a1IZ7Lf9TDSXiz4jJcPdYKdU=,iv:ww7Jm/hB40+4JmvcJ40/bJIBYjsOb2VS5vYd9XF9bQg=,tag:reLrb0vojDI+XTnYI2SIIQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
