# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: 0BSD

# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.2/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
data:
  TIMEZONE: "Europe/Copenhagen"
  CLUSTER_NAME: "home"
  DOMAIN: "finnes.dev"
  IP_ADDRESS: 192.121.119.137
  S3_ENDPOINT: "hel1.your-objectstorage.com"
  S3_BUCKET: "soupglasses"
