# SPDX-FileCopyrightText: Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: CC0-1.0

# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.2/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: gitea-status-token
stringData:
  token: ENC[AES256_GCM,data:9jKoRkGgyvbe+R9ga5lsRTKkCeWLbGYKB54MWYbEVc/EBO7viM7+Og==,iv:4i/kl0NJbWPQUifNrJG3Zu3CvrSSgC5RTYDyQGRXPzo=,tag:ip0Axm2t4ZsQeh42UGvDQQ==,type:str]
sops:
  age:
    - recipient: age16k03wpjydrcr2wk68f0q9ypdxvh7vsy0fpx4lq72nc50zln8xf3qvkjxas
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcGQ5MDlrSFpMV2VONk1j
        amN0bmxneHo0UE5FczdFa3RwMkZKN2RIaVJrCllBZnBIUTBqTzNWcTJlM1hhL3Yv
        K1ZJWHVCNENwTjZZTDZjYVdieEY0eG8KLS0tIEVlN05xMGJQRCs5MXh4bzdWOWJH
        b3JwRCs1ejJpdEVWaGY5ZmFNMGpHWEkK+xmQrd+9V8lyo4Jw8r0p40z423NNgHfu
        wcipXAoTEuwT0qMpJxoJINLGsvgdZ/d5ah/2IQkBq/+d2IUO4mzZlQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-17T12:40:25Z"
  mac: ENC[AES256_GCM,data:GlfsboHdy0JMFu/9r3Haxfcq9a3wO9WBAOoKcoFZz9OY0GhXcXjytHw8FM8vi1mIcukaxY7tE8GaIEdAwhvxPkkOc+vUAkDpwb/DDTbVXoQndGr1YqKwtIth9NIZhOmcSzmNTvLuR/vkDW+ykxQ/ihWz3SKb/CRO4Qy7oP7fHqc=,iv:OKpIS1Si4S7C5mKv3C0gDAZrF7YvYuaP8Z+xfow5nRo=,tag:Fhwun13efjp+D3LUAH4W/w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
