# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: 0BSD
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.2/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: gitea-status-token
stringData:
  token: ENC[AES256_GCM,data:Zjz0XVsFBTv1m2nhyV9RM0gdKlPDIc3YllznK9Q4PhglSfrPgbYGIg==,iv:rNGdhGQ1ddQ2y0wmXBrRjoZrHJWlNDe0sdyWB9S+0kA=,tag:8KKTRl9nStR6ZR17IVDpNA==,type:str]
sops:
  age:
    - recipient: age16k03wpjydrcr2wk68f0q9ypdxvh7vsy0fpx4lq72nc50zln8xf3qvkjxas
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcGQ5MDlrSFpMV2VONk1j
        amN0bmxneHo0UE5FczdFa3RwMkZKN2RIaVJrCllBZnBIUTBqTzNWcTJlM1hhL3Yv
        K1ZJWHVCNENwTjZZTDZjYVdieEY0eG8KLS0tIEVlN05xMGJQRCs5MXh4bzdWOWJH
        b3JwRCs1ejJpdEVWaGY5ZmFNMGpHWEkK+xmQrd+9V8lyo4Jw8r0p40z423NNgHfu
        wcipXAoTEuwT0qMpJxoJINLGsvgdZ/d5ah/2IQkBq/+d2IUO4mzZlQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-06T18:24:48Z"
  mac: ENC[AES256_GCM,data:sdx/Qy9hOLCnKKtXLA3AJbWx17/OaoLcJndPF6Xqq8BIo0OuaP2h0iNE9c8qcK8FAlyuspkS/ZTQnuB+KXJFN5G+R57YpBUmST43VcmT1Vqri7rBlfxLfoqyVHZrma1dPBeBSRjCmjHRp5ZsXM2pRpr0T3yLO4as2z9XQ0P5UAw=,iv:7wrzOL/j2I0iHeCZYi1crCfRflQNLq7JtbgIJdiFxZU=,tag:kVjtJ+/gxcu8aG+fpvgwrQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
