# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: 0BSD
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.2/secret-v1.json
#
# TODO: Replace placeholder values and encrypt with:
#   sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ldap-admin-credentials
stringData:
  ldap_bind_password: ENC[AES256_GCM,data:obvkIW1oo2tcP6cyXXYXZ+8lRduI3OX+zVs7xvf2Lk7N1xUDzLR9QR7b,iv:xjVh5BsBRvmfbyScRQIiGy6ry0F/If3b1vPaJRI6tO4=,tag:jKobsK6C/vo5HfGoR3H+ag==,type:str]
  auth_user_password: ENC[AES256_GCM,data:4BgAq8zZdzzC683DZL+GK+vhzSQ299YvL6tiZ5h4YfyY9VGc947k83Ho2TE=,iv:rcDJb1X6qKCZ6XqPu9fxEkHx7D8kT1HfjqB+ZkZsXpM=,tag:UhDhDe9uSK50lY+7anNj3w==,type:str]
  admin_password: ENC[AES256_GCM,data:NMqeS4IFOmQRdNVKcc6vqrtewAgZXjoqLDKnJjTDIis0KYW17IZm1n+zMGA=,iv:HVt/nwfbW2V4DjaFUxIZz9O7AFEsbmHwj0NHs8vIfrQ=,tag:3EKpLEZY0BK8dhWsrjAA0w==,type:str]
sops:
  age:
    - recipient: age16k03wpjydrcr2wk68f0q9ypdxvh7vsy0fpx4lq72nc50zln8xf3qvkjxas
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYU9ZZUp5aFYwaHRvL1c1
        bm1iR3dYVzlVQ2gzMHp3NnhYVkpqSmNXRkNzCi9WbzBQRHlXWEhkbFgvTFRaTGd1
        emxPVFpjUnR1YW1LZXhaV3ByNWhmNlUKLS0tIGVtM1RWVTNhaitIZkcwVlV0eWhw
        Wk9nMGRMU1p3MFIwYWVOaVhSaGI3dkUK/FVzirxj7+cWl32xu1vAexP445FmNpEK
        JjkpqbMjKYLMDqHHoOk+W1ofBbnpAAsecItYYxzGxwLlIm4i+UOIfA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T20:23:10Z"
  mac: ENC[AES256_GCM,data:imrMS8WhiB/iOl7ouvhGlmZRWsjT3y0XE8RX7+88iYTKIYSTkWNmyYE6a78deD9XbKFvFsWbbfsuxg/9vKKurfNLiM1inWdEEV5AhqGJjMXQtXzc8fvSAnfzYlUy1M5YbHZMUq35I9UWUZkhVPZWYvovX3S/BASVXB83RwrXpZ8=,iv:7NKfm211+kpXTrPlMVPACgnxV9uiOA/7+RxaVUVGpFg=,tag:hmDQgo/Dhx4tH48CwJ6adQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
