# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: 0BSD
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.2/secret-v1.json
#
# TODO: Replace placeholder values and encrypt with:
#   sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ldap-admin-credentials
stringData:
  #ENC[AES256_GCM,data:sivhlBSGjec8744zkZsZaf90SFOK8EY5/hSAG3BWsspk9BeJyshL3gdP2ReLwOyat0fbjxJCZgHbpnVfVQG0bcxS+GOJmxEqANGMz0yg,iv:odX5CzwSZv5iom9zhC97lKLGY1FX3WibzhGNsxPC83Q=,tag:Jw2fqAhd1CyIGbQxcUdQfg==,type:comment]
  ldap_bind_password: ENC[AES256_GCM,data:obvkIW1oo2tcP6cyXXYXZ+8lRduI3OX+zVs7xvf2Lk7N1xUDzLR9QR7b,iv:xjVh5BsBRvmfbyScRQIiGy6ry0F/If3b1vPaJRI6tO4=,tag:jKobsK6C/vo5HfGoR3H+ag==,type:str]
  admin_user_password_hash: ENC[AES256_GCM,data:o7YsG/S4/1SIN7i51AKRyKMwNhxlAMlzmmQNicYZVqFSmvkO71V3mTb9nhh+UdDRhJhsahSsme+JQx5EjLBTD12oVuFNAhBoN/7c+hJRwe693ze5ZbKFGdv43+TEdKG2fegKwiRSZIZX,iv:QkAKODlod0s0bD0Aq/9EkS4NgoGa4Xl/NRCp8gXH0SI=,tag:RpDQejild8lLuajlimcHQQ==,type:str]
  admin_password_hash: ENC[AES256_GCM,data:whB76KCSsR15TLOtJQcXCyKdozs3j+sYyCuzIXE216ZYq6Tat1PicNK2frdwBTa9I2M9mwSWvQPcWOqi7bJRJ9W6BzAHSS6yhjAPZtNkjaRPDCLqaOXh6yaruHo98GlBzI8ICgkRrdyd,iv:nLg+Q8p+YdDeSSR7IhWTG/X19z18FmDdPDbqhafgeps=,tag:4hyaruyi+qXg0JjqI1mEJw==,type:str]
sops:
  age:
    - recipient: age16k03wpjydrcr2wk68f0q9ypdxvh7vsy0fpx4lq72nc50zln8xf3qvkjxas
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYU9ZZUp5aFYwaHRvL1c1
        bm1iR3dYVzlVQ2gzMHp3NnhYVkpqSmNXRkNzCi9WbzBQRHlXWEhkbFgvTFRaTGd1
        emxPVFpjUnR1YW1LZXhaV3ByNWhmNlUKLS0tIGVtM1RWVTNhaitIZkcwVlV0eWhw
        Wk9nMGRMU1p3MFIwYWVOaVhSaGI3dkUK/FVzirxj7+cWl32xu1vAexP445FmNpEK
        JjkpqbMjKYLMDqHHoOk+W1ofBbnpAAsecItYYxzGxwLlIm4i+UOIfA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-06T17:28:51Z"
  mac: ENC[AES256_GCM,data:sCNbe99clv6nQfl336SPaINE/69s7VCt066bfkCZG76k+CGRVQGUEBpjWr4dTrgNktN0Qlzhrcw0IxgU3hbc9s7x+yBs+pIaB2QTvTYe5g9JoHtLvrS7trNMSwpmIMhWoZzyuPZW+m/gJXxkc8CVsd9fCEyYvBeJIh/14mMwXXc=,iv:Z+huqqvlcbFCpskTZwW7ez0iacQdA9JBYd+Ks6PrMO0=,tag:ttop1Lpa+21agvMMcWX7sA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
