# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: 0BSD

apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: ldap-system-users
spec:
  approvePlan: auto
  interval: 1h
  path: ./tofu/ldap-system-users
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  vars:
    - name: use_sops
      value: "false"
    - name: domain
      value: ${DOMAIN}
  runnerPodTemplate:
    spec:
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: cluster-secrets
              key: SECRET_AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: cluster-secrets
              key: SECRET_AWS_SECRET_ACCESS_KEY
  varsFrom:
    - kind: Secret
      name: ldap-admin-credentials
