# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: 0BSD

apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: ldap-system-users
spec:
  approvePlan: auto
  interval: 1h
  path: ./tofu/ldap-system-users
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  vars:
    - name: domain
      value: ${DOMAIN}
  varsFrom:
    - kind: Secret
      name: ldap-admin-credentials
