# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: MIT
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
spec:
  interval: 1h
  chart:
    spec:
      chart: minecraft
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    resources:
      requests:
        memory: 1024M
        cpu: 1000m
    extraEnv:
      USER_API_PROVIDER: mojang
      EXISTING_WHITELIST_FILE: SYNCHRONIZE
      EXISTING_OPS_FILE: SYNCHRONIZE
      WHITELIST:
        valueFrom:
          secretKeyRef:
            name: minecraft
            key: WHITELIST
      OPS:
        valueFrom:
          secretKeyRef:
            name: minecraft
            key: OPS
    minecraftServer:
      memory: 4096M
      pvp: true
      eula: true
      type: FABRIC
      version: 1.21.10
      modrinth:
        projects:
          - fabric-api
          - lithium
          - scalablelux
          - c2me-fabric
          - ferrite-core
          - no-chat-reports
        downloadDependencies: none
        allowedVersionType: release
      gamemode: survival
      difficulty: hard
      levelType: normal
      allowNether: true
      spawnAnimals: true
      spawnMonsters: true
      motd: "&d&lS&5&lo&9&lf&b&li&a&le&e&l'&6&ls &c&lC&d&lo&5&lr&9&ln&b&le&a&lr"
      maxPlayers: 20
      viewDistance: 16
      spawnProtection: 0
      generateStructures: true
      overrideServerProperties: true
      serviceType: LoadBalancer
      loadBalancerClass: tailscale
    serviceAnnotations:
      external-dns.alpha.kubernetes.io/hostname: mc.${SECRET_DOMAIN}
    persistence:
      storageClass: openebs-hostpath
      dataDir:
        enabled: true
        size: 10Gi
        accessModes:
          - ReadWriteOnce
