# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: 0BSD
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.2/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: minecraft
stringData:
  WHITELIST: ENC[AES256_GCM,data:E9kpxsmV6FUmxFkb97cG16PwPJa7tjc+Vd04hw==,iv:IPlQNLexko3oOdn1AX8q7OWfaISQAFNDeI64nCQTYQU=,tag:GMa6AOvS4E5KuwFxSEb8Xg==,type:str]
  OPS: ENC[AES256_GCM,data:buQVm/WIFNL/wVVy,iv:amWKsNUIcxcLcRXdvxmhArmSTKay5Tm7WwiyEXhMGFg=,tag:/MiQ8qFMmTVLrVbsFmkd1A==,type:str]
sops:
  age:
    - recipient: age16k03wpjydrcr2wk68f0q9ypdxvh7vsy0fpx4lq72nc50zln8xf3qvkjxas
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkeFhFYlA2blVvQUZqb3pj
        ZUFMQm1JWURqa0cySVRwQmN2dkp0ZmNxS1JJCkdaSHpDUnBmalFqTVV3djZNczZJ
        azFYSk5hTTV5WEdNUjVJUDRvYUw0TlUKLS0tIHlQa08zWTVHV1N0bjM4eFQrNHhi
        d2FwZnhMTnoxSW13ZWpmaytCRHlyWFkKiGvKGUh87pArixMQAqh9tYcOOd1YpSdv
        t2hDZd96ROYmeAIQAsEBE6r1R0OFJGkvSGDZmPZvEvQIsgQVp7sltA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T15:49:45Z"
  mac: ENC[AES256_GCM,data:9Z/8g+wFCwLc2+Nn3dwT618ZXVFjpdCKNoa2Toe2RpLr3wPunww+XPuiRyfDKKSGhpxfsIHTg2cFE2fLTqxC42ZVkyrjbmjqIvhzNhP0AXifoCNJ0AqAEMD6kFEjbL72CYrHX0JzkxlgP0nNyKL+OE8aUwQ7Gyrc/hiHDWL4+tY=,iv:wBQmiOItsUqrja0/zT3xCDeRWqvVA23A8xdyJTMKhS4=,tag:hHi0blezEy0/mRpdF4iJEg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
