# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: 0BSD
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.2/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: canaille
stringData:
  SECRET_KEY: ENC[AES256_GCM,data:3j+W7KMqOcUJh4OOlv3sS1Q4eVjNFo1l5Ilp64OPEgXVNcgzdgsuP4Jk,iv:pCH9YY0kjTbpfJrB7e7pj4OTFSlSgaP2WynBPbL7KJU=,tag:cPWXK1Nu4uq22R1rTNnB6w==,type:str]
  BIND_PW: ENC[AES256_GCM,data:+hqhB1e/TrBbLDaA1I1YPC3eeCFMCUNvCC3RXZHDVttwtNyloUDCcUnzLGw=,iv:fN/RSu/TpCCuc7SVGIEO4sYLvrZIKyqegN5UNCt1t08=,tag:VEqCHkL9lvkSvJ3dx7zY3Q==,type:str]
sops:
  age:
    - recipient: age16k03wpjydrcr2wk68f0q9ypdxvh7vsy0fpx4lq72nc50zln8xf3qvkjxas
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVFU1cjgvL2F4N0ltSWMw
        QmR6Y2tvbUwyWHh1REduSHNleE9CTWswa0FrClYzbjk4aGxOelZCUHhaQVhYTUhK
        a3BkY3FyUHZOQzkwSUpKcDhOaEUybVUKLS0tIEVyREJjaWs2N2w1MFpDL0NFeVB3
        NVowZUoweklrQ1FtbUd0Ulc0OVBES1UK0/9bUuKvy0PuLSwc2zhzcSsoTyc/VlhH
        gaT9ZFtpn+m8EBCA2oXT85tRgEysZ28qz/Dm9YlY9BPgOexqV0/yZg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T20:23:06Z"
  mac: ENC[AES256_GCM,data:hCHGRZGQuBySoVo01eSo+I7CxyLWDTZvl1/W9gTKBg9lTj8G4x9QkkWjYCCm+DaWtfINsGrUYd9vG7srjgO3kzsmbEiB0NiWFxjjqo5TmkkcYkd1bhC7mHfemzRIRCUdUtg7qZsE7O4IlcRbcSqAlRakOmm3lT3ga6Cb4r/cLPg=,iv:5Oi2KrNVwDtrwLoD7F2inCiL9u83pIKPZ1wE7lMoQS0=,tag:VAN4EIaTYsOremYc06SBJA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
