# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: 0BSD
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.2/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: openldap
stringData:
  LDAP_ROOT_PASSWORD: ENC[AES256_GCM,data:cIlrB44Y3Siddr+zRz6gkY1txyOWwFX4C8Ef/qEX9RIlk9J+YrOEBHg9,iv:MdHscqH2/JZ6hqJskP1lAM+rtMFFYx0xeGzfgpwAKyY=,tag:qtrWpQ4+XgRGTbuP739PSg==,type:str]
sops:
  age:
    - recipient: age16k03wpjydrcr2wk68f0q9ypdxvh7vsy0fpx4lq72nc50zln8xf3qvkjxas
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VWIycnV5UHl2eFFURmdS
        bWlPV0tJK3Y1SEQ1RnZFQ1ZmdHExQXJiVjJrCnVicHZJVXNsZnVpUjFLRXJLdUc2
        dXF4ZkZBcUEwbi80Y2xsM3lsZ0RCR1EKLS0tIDduSms3dXdZb1NqUi9UU0JTMkZG
        eUtCSmh1azlwTmxQalhuWlk2aEIrQmMKC3JBALGb0aUYS7NN6CfBwExKFsvkVG3C
        wU4y7EEAmdlSKLtEsPTzjWvejg3QhHMQracxkQqrsQhYgOWzxnXzDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T20:23:11Z"
  mac: ENC[AES256_GCM,data:JThu3iR2nIi+N0UEC+iT1KUpJo09zHHODLoRWFKBydnvPRGJv4PQ+WavgnH6mfLYl+bjvb1VG6I9XVl9lnTONWLUBvXZHMZG78lOpuRuw3p2T/QuyZEobpeFuXLkKOSkcSMdvTF6q5KR0Mxk52iBXONo4LuqfCQvDX0DIORw+mM=,iv:lj9l33b6q0HJQ2QTzgYsV2gPlX3zGkN7zibME8vwHfg=,tag:JHZW51q7Hj52A9RhgFw34g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
