# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: 0BSD
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.2/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
stringData:
  client_id: ENC[AES256_GCM,data:9VHiEbTH9+eGI8C9BOFpEdo=,iv:U/2AXDN28aiM5fGJkv4g0XshxLO0RmoE2oLZ3/UHWho=,tag:ejYvhu7pAQUUCTwF7Qj0ow==,type:str]
  client_secret: ENC[AES256_GCM,data:o1vz+lNzeHjGZBEdn7gEEBp2QOS+trjZmeVS2OUMBUXv+DFndO977z3ibXYlV+bgIfJH99ucfT9Smo6mvbgQ,iv:daor5U4dVwFlWUg342do2prbWAW7/WAflWk+8hM0N+0=,tag:GM3DEVQDILUc4zv+q3SQuw==,type:str]
sops:
  age:
    - recipient: age16k03wpjydrcr2wk68f0q9ypdxvh7vsy0fpx4lq72nc50zln8xf3qvkjxas
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuU1Z2OVZ5emN4M240QkRM
        U0xYZTV1enFmaE5Rd1lLQkRwS3MxUDBPWER3CnJ6YWlZM1pnWW8ySnNsd250eFJu
        bnppZzN4RW0xOVlnWUxrZk5TbDEvY1UKLS0tIHBDdzJob04rTFEzc2hSZEU4bno3
        dC92WUdPek1rYXZBZUlPdjJtUVdUa0EKFZ0gYs7pd06erpXdAZUY2xh+qyWUCdmH
        E6+dq6QMkQE+MCdlqHZ2/jamuYoDq4FeYvsBWowP5PlZ/yLOHf78hw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-11T19:14:50Z"
  mac: ENC[AES256_GCM,data:gVPqS1yquqVlBR76aiEu5fCTw2vrWmLooT0buvxhDZb0pHAvL7f5rIeaXYu3iyoJSjw/n6Gmvi7epjnnUBgiGl09zC7rKUb7zsD/x8kgm+K/4+Nz1WhXdmskAg+a7vaYayRXTT9VAZvfL2J4GujHIkmCZGDsqwoOIsmtpqT8xqg=,iv:tTmBb1CPa/IKyqcobtUg4poiu5+Evw01bjJ0jJ7tvBs=,tag:5LyCCDOvwQe98ehVE3OhcA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
