# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: 0BSD
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.2/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-status-token
stringData:
  token: ENC[AES256_GCM,data:dSXOYfzvntXzkOvlr2jWJSwn0nToLMkGtAafJpL6vytnfRlggcFQ4w==,iv:hnH70j88y4URsRrt5V9GmVf47CoeOFPX4KRlwF0B6i4=,tag:U3K/5SkLUNEQsaCwiF//qw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcGQ5MDlrSFpMV2VONk1j
        amN0bmxneHo0UE5FczdFa3RwMkZKN2RIaVJrCllBZnBIUTBqTzNWcTJlM1hhL3Yv
        K1ZJWHVCNENwTjZZTDZjYVdieEY0eG8KLS0tIEVlN05xMGJQRCs5MXh4bzdWOWJH
        b3JwRCs1ejJpdEVWaGY5ZmFNMGpHWEkK+xmQrd+9V8lyo4Jw8r0p40z423NNgHfu
        wcipXAoTEuwT0qMpJxoJINLGsvgdZ/d5ah/2IQkBq/+d2IUO4mzZlQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16k03wpjydrcr2wk68f0q9ypdxvh7vsy0fpx4lq72nc50zln8xf3qvkjxas
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-27T11:34:13Z"
  mac: ENC[AES256_GCM,data:mVMxuaAiw8c1h03CrmwzWA+2Xv8goXxjTAMVIRqLMjFWkxIJEHQsnTKCBRa/SUgocmFMg2THJ5O+vqac2JxDXY8tVBXaFGVB45VvnOOY3qAtfH6fm5Mklho7SXW9OIeo3nDcvkRPG7VSckJHN29Sv+6vVTlH+rmQ0XfcnthvmcE=,iv:HXAXDdzOxNGkza0H4P2e9KYgo0dukHr25grLpCD2kNw=,tag:LbdblFYSuV6FpbKGgF6LCQ==,type:str]
  version: 3.13.3
