# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: 0BSD
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.2/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:N/Jl0ECBBEleMOsSahrU1MFMDQZYpkbhW9vKKNx7KMAuwqKxPMKpxbu587CfPiTkAsjcGs8Ax0gDOFiP2avTS1/jIq5pCloygRKHxmpZdJOnTl5ZdIUpnVcfdPmbIM5xnSLe9qWmydZlXeEUuPFd8LnByUCeCgE0zVLYb1U4ACq+LCPpJaJQTQjzAEFYaRVpe7QzjXXODNt+i8LZOt3ZxwsxbBqxQ+HIWngbruTJUu8/3vQ5tHVhEV2W1AcI,iv:EZGShqCyy1YtXDlehcohplFaurdCGtixzfYy8I1q5qo=,tag:VmNs6Cvju75o17eAOx16ew==,type:str]
sops:
  age:
    - recipient: age16k03wpjydrcr2wk68f0q9ypdxvh7vsy0fpx4lq72nc50zln8xf3qvkjxas
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYmNGS3V0S2MrM09TWGRh
        SU5adXBqeEhmYzFPR3dzYS9nVEVPcFB6c3hJCjQ1eWl0MXE2WE03elpwajJUbFpZ
        TXlMYUNBUnlUN09CZTdJaTRFQ2MvZ0UKLS0tIGtsbklZbjlvU1VxdnBTYWlMOTNC
        ZEFvM3NWUDZQZDlNdmFCTDBKS0tWaEUKIFzqxP5XaqCLyYDe4uUPptkjsWAd2y8G
        VfXZCpBbrRkRBw0zogWJohvAKfArxwT6Y72OPUyh4M1/1mlItHkupA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-03T11:06:37Z"
  mac: ENC[AES256_GCM,data:277+bED1Gh0IbpWAifKE5EF45Ft4OHFAHyc0vYtwbc1+Tt5d6uPrFmNYd0vIx8St8UonuKemhKqxlfFrQlGxjuGLabLB1wFnV6ZEt+sd4yCCpn0fVmOhBx9xlNLU7EEr19Mb3A8uNj+Gb2iD1b1MZ7uZTxd5cZeP+Bh9yvseDls=,iv:hBTbO8fa10NwoJ/H0g2Fmm8sUMfpvjrbuJpcaq8AbR8=,tag:42DLGX0m8jBvhwKrTol7mA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
