# SPDX-FileCopyrightText: Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: CC0-1.0

# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.2/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: gitea-status-token
stringData:
  age.agekey: ENC[AES256_GCM,data:b4TDbt0FyZo9mqX0alAFPcl068Tf6iG5IB9NYHG+1zr2/DjWlwpxWVdj6UvyYx9r7l4OUgQIUCl+pEjILxHfIfYz19RE25epoT+Lq4VciE9Yi3X0+UrAVf4Yto+GT/OyctqhSOHg2fr4s50CndE4rVlIOyC1xb6ApFrOh3EJequg7+sKZqJavzGcxASOsbA3xIjC3hn6wEJp9glwM0wGmEl9WIKki1P16qW91LdB5HhbmgFBCzs2U4Z8jFJo,iv:nTralUUuEJMgN5URLx+4SyL7XCbUXB0+gc95asq7kC0=,tag:pYVx0537P4PXXnfGhfaeDw==,type:str]
sops:
  age:
    - recipient: age16k03wpjydrcr2wk68f0q9ypdxvh7vsy0fpx4lq72nc50zln8xf3qvkjxas
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRY3ZuYWNHV3JXeC9leWtq
        T2xWUjN6Um1QM0pvZGdNMXBmOFlvVG15ZHpJCjBiWkhGNDM0OWgrSDVKMXh4T2sx
        K1p1SUtmZmtaQlVLRUk3MDlWZTlQM3cKLS0tIDVKUE90TEt3Y3MxZGNVUG81ZDNZ
        Q1Y1UHdrZ0FFd3JLV1ZQMXd2NFRLckkK9omuLsEtlQKoeRO2sgxAtp5aJYei3gP3
        oM4uZeOgxQOwa58Eex2vjKbzlVaDNgX5mKj9Hg2ysYBAE1Zqx74Z5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-17T12:45:09Z"
  mac: ENC[AES256_GCM,data:kJsI3NbdFF5eQMEoPOFxfCtzvWuzMnS2+8M/TNC9/xPgtaODR6lmMFxbl2nLIq3Lp2bDRb6nBloLa0LA0tzgfk3tehI/9R3krvTPPx67sbejUHU18GeYgLTEmC0lrTbccKN+iNZEN5Z2aUx64TDnzP6Yf2I8nn1BxGgZwqJiG1Y=,iv:KYQyiedWNGE0jI4ZWxopHUk6VOXQICAOqy+v4NFFGGY=,tag:cb5hI/I+HtaFSY2N/algUA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
