# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: 0BSD
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.33.2/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ovh-api-key
stringData:
  OVH_APPLICATION_KEY: ENC[AES256_GCM,data:by7lW433wnytUyQT+y4Xxg==,iv:O5Trsk+TjC4z3iy4f5tviqqLNtrRRjCqfYvKjjdomp8=,tag:5zcDIOw82tRG5TOpYOPOXA==,type:str]
  OVH_APPLICATION_SECRET: ENC[AES256_GCM,data:9B6/+HML5sqSJ7pspIKgEe60w40ITZaHgzxYpIXJLsk=,iv:Ig6PafVBoHbbBPJg3doCPo9zXw9xUjVUsUeeMvRcQlw=,tag:r1buuVdW1jnOYP1Fus4swQ==,type:str]
  OVH_CONSUMER_KEY: ENC[AES256_GCM,data:8VtKSsHqFtAAubzwNcwtXiHDHmW/nAVmh5jKKYA9Sv8=,iv:60Pq9ItqQ9ItEkM0AXb87f8rESRdyYyMEgKbxHzqO+8=,tag:b0JBJSyqMou68kRYphwDEw==,type:str]
sops:
  age:
    - recipient: age16k03wpjydrcr2wk68f0q9ypdxvh7vsy0fpx4lq72nc50zln8xf3qvkjxas
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkeFhFYlA2blVvQUZqb3pj
        ZUFMQm1JWURqa0cySVRwQmN2dkp0ZmNxS1JJCkdaSHpDUnBmalFqTVV3djZNczZJ
        azFYSk5hTTV5WEdNUjVJUDRvYUw0TlUKLS0tIHlQa08zWTVHV1N0bjM4eFQrNHhi
        d2FwZnhMTnoxSW13ZWpmaytCRHlyWFkKiGvKGUh87pArixMQAqh9tYcOOd1YpSdv
        t2hDZd96ROYmeAIQAsEBE6r1R0OFJGkvSGDZmPZvEvQIsgQVp7sltA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-24T15:42:51Z"
  mac: ENC[AES256_GCM,data:rC/JkYLMCWsMxcJDAoZIBe6ERdlFx1sqO3RsiPhZuVpLntaXpVW2kJRqvBjDYTtOXP9awx3JojNGg7CbyJ3DLKBS3/0j1r4WgGS9lUs79mmppFzjsqYwkiKwiQ2hVQuOVRmqgdZImYWY0+JbRQiqtfj4bZwt3whlr0PRGZPgVow=,iv:60N9cYBHEfXwXcU49ziSdNOp0kR0f3tmxhAWxmsIct8=,tag:V/eg4I+Jq+u9ku4TXYExKQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
