# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: 0BSD

# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.32.2-standalone-strict/storageclass-storage-v1.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfs
provisioner: zfs.csi.openebs.io
allowVolumeExpansion: true
parameters:
  recordsize: "128k"
  compression: "lz4"
  dedup: "off"
  fstype: "zfs"
  poolname: "zfspool"
allowedTopologies:
  - matchLabelExpressions:
      - key: kubernetes.io/hostname
        values:
          - nas
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.32.2-standalone-strict/storageclass-storage-v1.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfs-data
provisioner: zfs.csi.openebs.io
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  recordsize: "1M"
  compression: "lz4"
  dedup: "off"
  fstype: "zfs"
  shared: "yes"
  poolname: "zfspool"
allowedTopologies:
  - matchLabelExpressions:
      - key: kubernetes.io/hostname
        values:
          - nas
