# SPDX-FileCopyrightText: 2025 Sofie <sofie+git@mailbox.org>
#
# SPDX-License-Identifier: MIT

# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
components:
  - ../../components/common
resources:
  - ./external-dns/ks.yaml
  - ./ingress-nginx/ks.yaml
  - ./tailscale-operator/ks.yaml
patches:
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        labels:
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/warn: privileged
        name: not-used
    target:
      kind: Namespace
